name: Handles incoming repository_dispatch events
on: repository_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build event
      if: github.event.action == 'build'
      run: |
        echo "Received 'build' event from ${{ github.event.repository.name}}..."
